# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'blbl_gui.py'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys
from PyQt5 import QtCore, QtGui
from PyQt5.QtCore import  QEventLoop, QTimer
from PyQt5.QtWidgets import QApplication, QMainWindow
from F1 import *
from about import *
from list import *



class ListWindow(QMainWindow, Ui_List):
    def __init__(self, parent=None):
        super(ListWindow, self).__init__(parent)
        self.setupUi(self)

class blWindow(QMainWindow, Ui_blbldl):
    def __init__(self, parent=None):
        super(blWindow, self).__init__(parent)
        self.setupUi(self)


class AboutWindow(QMainWindow, Ui_About):
    def __init__(self, parent=None):
        super(AboutWindow, self).__init__(parent)
        self.setupUi(self)



def main():
    app = QApplication(sys.argv)
    #QApplication.setQuitOnLastWindowClosed(False)
    myWin = blWindow()
    about = AboutWindow()
    listw = ListWindow()
    myWin.about.triggered.connect(about.show)
    myWin.exit.triggered.connect(sys.exit)
    myWin.queue.triggered.connect(listw.show)
    myWin.show()
    sys.exit(app.exec_())
if __name__ == '__main__':
    main()
