# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_blbldl(object):
    def setupUi(self, blbldl):
        blbldl.setObjectName("blbldl")
        blbldl.resize(400, 600)
        blbldl.setMinimumSize(QtCore.QSize(400, 600))
        blbldl.setMaximumSize(QtCore.QSize(400, 600))
        self.centralwidget = QtWidgets.QWidget(blbldl)
        self.centralwidget.setObjectName("centralwidget")
        self.link = QtWidgets.QLineEdit(self.centralwidget)
        self.link.setGeometry(QtCore.QRect(50, 110, 301, 51))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(11)
        self.link.setFont(font)
        self.link.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.link.setObjectName("link")
        self.next = QtWidgets.QPushButton(self.centralwidget)
        self.next.setGeometry(QtCore.QRect(130, 190, 131, 41))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(11)
        self.next.setFont(font)
        self.next.setObjectName("next")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(50, 280, 311, 234))
        self.groupBox.setObjectName("groupBox")
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setGeometry(QtCore.QRect(20, 140, 281, 31))
        self.comboBox.setEditable(False)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(100, 180, 101, 41))
        self.pushButton.setObjectName("pushButton")
        self.label_status = QtWidgets.QLabel(self.groupBox)
        self.label_status.setGeometry(QtCore.QRect(20, 30, 271, 71))
        self.label_status.setTextFormat(QtCore.Qt.PlainText)
        self.label_status.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_status.setObjectName("label_status")
        self.label_episode = QtWidgets.QLabel(self.groupBox)
        self.label_episode.setGeometry(QtCore.QRect(20, 120, 71, 16))
        self.label_episode.setObjectName("label_episode")
        blbldl.setCentralWidget(self.centralwidget)
        self.Advance = QtWidgets.QPushButton(self.centralwidget)
        self.Advance.setGeometry(QtCore.QRect(313, 240, 51, 24))
        self.Advance.setIconSize(QtCore.QSize(24, 24))
        self.Advance.setObjectName("Advance")
        blbldl.setCentralWidget(self.centralwidget)

        self.retranslateUi(blbldl)
        self.next.clicked.connect(blbldl.repaint)
        QtCore.QMetaObject.connectSlotsByName(blbldl)

    def retranslateUi(self, blbldl):
        _translate = QtCore.QCoreApplication.translate
        blbldl.setWindowTitle(_translate("blbldl", "MainWindow"))
        self.link.setPlaceholderText(_translate("blbldl", "请输入视频链接或视频号"))
        self.next.setText(_translate("blbldl", "下一步"))
        self.groupBox.setTitle(_translate("blbldl", "状态"))
        self.comboBox.setItemText(0, _translate("blbldl", "1"))
        self.comboBox.setItemText(1, _translate("blbldl", "2"))
        self.comboBox.setItemText(2, _translate("blbldl", "3"))
        self.comboBox.setItemText(3, _translate("blbldl", "4"))
        self.pushButton.setText(_translate("blbldl", "Download"))
        self.label_status.setText(_translate("blbldl", "欢迎使用blblDL\n""made by xy\n"""))
        self.label_episode.setText(_translate("blbldl", "请选择集数："))
        self.Advance.setText(_translate("blbldl", "高级>>"))
